<a href="https://colab.research.google.com/github/manhtuan09072020-afk/TH_DEEP_LEARNING/blob/main/buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

my_list = [1, 2, 3, 5]
print('Python list:', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

Python list: [1, 2, 3, 5]
Numpy array: [1 2 3 5]

In [ ]:
import numpy as np

a = mp.array([1, 9, 15, 39])
print(a)

In [ ]:
import numpy as np

c = np.array([(1, 2, 3),
            (4, 5, 6)
            ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

In [ ]:
import numpy as np

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)

In [ ]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
              ])
print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshaped (3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('reshaped (3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('reshaped (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshaped (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshaped (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshaped (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]

In [ ]:
import numpy as np

e = np.array([[1., 2., 3,], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
             [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]

In [ ]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]

In [ ]:
import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [63 39 35 17 93]
Random 2-D array
 [[16 61 42 87]
 [72 42 13 44]
 [41 66 31 30]]
Random 3-D array
 [[[61 60 19]
  [44 32  7]
  [ 6 81 30]
  [27 72 18]]

 [[91 47 26]
  [82 89  6]
  [21 72 68]
  [87 22 75]]

 [[34 65 75]
  [48 83 55]
  [35 99 25]
  [64 77 75]]]

In [ ]:
import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.5347184  0.96525784 0.18282074 0.04303689 0.97073729]
Random 2-D array
 [[0.71104233 0.70670461 0.43373006 0.45488646]
 [0.73971889 0.23963687 0.87736622 0.49380248]
 [0.83190669 0.5144039  0.73518485 0.43620639]]
Random 3-D array
 [[[0.90644088 0.43647597 0.54193393]
  [0.45998314 0.26543277 0.15998311]
  [0.80177579 0.85667114 0.13864064]
  [0.99608286 0.32132838 0.81948106]]

 [[0.43403957 0.09452318 0.92551626]
  [0.58450187 0.83268805 0.82148182]
  [0.44156947 0.00678054 0.50309023]
  [0.76085722 0.49275061 0.20604911]]

 [[0.80506476 0.64544097 0.47587351]
  [0.54174566 0.26032511 0.86708432]
  [0.1179379  0.47243001 0.43308138]
  [0.89963772 0.40694418 0.91100589]]]

In [ ]:
import numpy as np

a = np.random.normal(5, 0.5, 10)
print(a)

[5.23304895 4.88709105 5.61152117 5.13181004 4.74152122 4.65804645
 5.87584187 5.0873018  5.15276365 4.4350119 ]

In [ ]:
import numpy as np

a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size =(3, 5))
print(b)

20
[[12 12 16 10 20]
 [20 14  6 10 20]
 [10 12  6 20 12]]

In [ ]:
import pandas as pd
s = pd.Series([12, -4, 7, 9])
print (s)

0    12
1    -4
2     7
3     9
dtype: int64

In [ ]:
import pandas as pd

s = pd.Series([12, -4, 7, 9], index=['a', 'b', 'c', 'd'])

print(s)

print("Dữ liệu:", s.values)

print("Chỉ số:", s.index)

a    12
b    -4
c     7
d     9
dtype: int64
Dữ liệu: [12 -4  7  9]
Chỉ số: Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
import pandas as pd


data = {
    'color': ['blue', 'green', 'yellow', 'red', 'white'],
    'object': ['ball', 'pen', 'pencil', 'paper', 'mug'],
    'price': [1.2, 1.0, 0.6, 0.9, 1.7]
}
frame = pd.DataFrame(data)
frame

    color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [ ]:
import pandas as pd

frame2 = pd.DataFrame(data, columns=['object', 'price'])
frame2

   object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [ ]:
import pandas as pd

frame2['type'] = 'nomal'
frame2

   object  price   type
0    ball    1.2  nomal
1     pen    1.0  nomal
2  pencil    0.6  nomal
3   paper    0.9  nomal
4     mug    1.7  nomal

In [ ]:
import pandas as pd

for i in range(len(frame2)):
  if frame2['price'][i] > 1.0:
    frame2.loc[i, 'type'] = 'good'
frame2

   object  price   type
0    ball    1.2   good
1     pen    1.0  nomal
2  pencil    0.6  nomal
3   paper    0.9  nomal
4     mug    1.7   good

In [ ]:
import pandas as pd

frame2['discount'] = frame2['price'] * 0.02
frame2

   object  price   type  discount
0    ball    1.2   good     0.024
1     pen    1.0  nomal     0.020
2  pencil    0.6  nomal     0.012
3   paper    0.9  nomal     0.018
4     mug    1.7   good     0.034

In [ ]:
import pandas as pd

frame2['price_afterdiscount'] = frame2['price'] - frame2['discount']
frame2

   object  price   type  discount  price_afterdiscount
0    ball    1.2   good     0.024                1.176
1     pen    1.0  nomal     0.020                0.980
2  pencil    0.6  nomal     0.012                0.588
3   paper    0.9  nomal     0.018                0.882
4     mug    1.7   good     0.034                1.666

In [ ]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello HUIT', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello HUIT', shape=(), dtype=string)

In [ ]:
import tensorflow as tf
import numpy as np

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

rank_2_tensor = tf.constant([[1, 2],
                            [3, 4],
                             [5, 6]], dtype = tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)

In [ ]:
import tensorflow as tf
import numpy as np

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>

In [ ]:
import tensorflow as tf
import numpy as np

t_zero = tf.zeros(10)
print(t_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

t_2_zero = tf.zeros(3, 3)
print(t_2_zero)

tf.Tensor([0 0 0], shape=(3,), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

t_1 = tf.fill(3, 10)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.normal([3, 3])
print(range_tensor)

tf.Tensor(
[[-0.15662181 -0.41067278 -0.18883672]
 [-1.2882875  -1.0100564  -0.42272955]
 [-0.76662093 -1.3667774   0.5318562 ]], shape=(3, 3), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([ 1.2812628  -0.31084996  0.5806323  -0.45187727 -0.43606693], shape=(5,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

tf.Tensor([ 0.27992073 -1.157786    0.36676055 -1.4693816  -1.1439569 ], shape=(5,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

tf.Tensor(
[[-0.37850836  0.98563176]
 [ 0.65273726 -0.21796243]
 [-0.20549588 -0.33522785]], shape=(3, 2), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

tf.Tensor(
[[[ 1.5087457   0.7818283 ]
  [-1.0505396   0.1107716 ]]

 [[-1.0989671  -0.25809166]
  [ 1.9564136  -0.27501768]]

 [[-0.42893428  0.127362  ]
  [-0.87089354 -0.89930606]]], shape=(3, 2, 2), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[10.058577 15.849155]
 [14.363612 12.143196]
 [14.96141  18.454899]], shape=(3, 2), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[[17.691746  11.08424   16.578224  15.494313  18.9686   ]
  [18.493073  19.054596  18.043694  13.745194  13.470035 ]]

 [[19.025417  10.288971  17.853085  14.612869  13.736227 ]
  [19.9437    12.269388  18.151045  14.650479  16.580809 ]]

 [[14.0450115 15.3850355 19.628056  17.823826  10.687901 ]
  [19.325418  15.093984  13.155136  13.383647  18.86617  ]]], shape=(3, 2, 5), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int ,'---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>

In [ ]:
import tensorflow as tf
import numpy as np

x = tf.constant(2, dtype = tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a, b)
d = a + b

print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a, b)
d = a * b

print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)

In [ ]:
import tensorflow as tf
import numpy as np

a = tf.constant([6. , 6., 6.])
b = tf.constant([4. , 4., 4.])
c = tf.constant([3. , 3., 3.])
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)

In [ ]:
import tensorflow as tf
import numpy as np

t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)

In [2]:
import tensorflow as tf
import numpy as np

t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])
dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)

In [3]:
import numpy as np
import tensorflow as tf

toan = tf.Variable(8.5, dtype = tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]

In [4]:
import numpy as np
import tensorflow as tf

toan = tf.Variable(8.5, dtype = tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>

In [5]:
import numpy as np
import tensorflow as tf

toan = tf.Variable(8.5, dtype = tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
diem.assign_add([1, 1])
print(diem)
diem.assign_sub([1, 1])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>

In [6]:
import numpy as np
import tensorflow as tf

def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

a_function_that_user_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
print(orig_value)

tf_function_value = a_function_that_user_a_graph(x1, y1, b1).numpy()
print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]
[[12.]]

In [7]:
import numpy as np
import tensorflow as tf

def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return inner_function(x, y, b)

rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]

In [8]:
import numpy as np
import tensorflow as tf

class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super() .__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train")
  def __call__(self, x):
    return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name = "simple")

rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variable', simple_module.trainable_variables)
print('All variable', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variable (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variable (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train:0' shape=() dtype=float32, numpy=5.0>)

In [9]:
import numpy as np
import tensorflow as tf

chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=simple_module)
checkpoint.write(chkp_path)

'my_checkpoint'

In [15]:
import numpy as np
import tensorflow as tf

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.w = tf.Variable([[0.36512682, 0.0],
                              [0.36512682, 0.0],
                              [0.36512682, 0.0]], name='w')
        self.b = tf.Variable([0.0, 0.0], name='b')

    def __call__(self, x):
        return tf.matmul(x, self.w) + self.b

new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint").expect_partial()

print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[2.1907609 0.       ]], shape=(1, 2), dtype=float32)

In [17]:
import tensorflow as tf

tensor_1 = tf.zeros([2, 3])
print("Câu 1:\n", tensor_1)

X = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_2 = tf.zeros_like(X)
print("\nCâu 2:\n", tensor_2)

tensor_3 = tf.fill([3, 2], 5)
print("\nCâu 3:\n", tensor_3)

tensor_4 = tf.linspace(6.0, 10.0, 50)
print("\nCâu 4:\n", tensor_4)

tensor_5 = tf.range(10, 101, delta=2)
print("\nCâu 5:\n", tensor_5)

tensor_6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print("\nCâu 6:\n", tensor_6)

tensor_7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print("\nCâu 7:\n", tensor_7)

Câu 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

Câu 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)

Câu 3:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)

Câu 4:
 tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)

Câu 5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)

Câu 6:
 tf.Tensor(
[[ 3.7385414  -3.1935756 ]
 [ 3.6131935   0.82632184]
 [ 0.578637    2.50738   ]], shape=(3, 2), dtype=float32)

Câu 7:
 tf.Tensor(
[[0.39399552 0.6938262 ]
 [1.2627542  1.0410419 ]
 [0.8012898  0.7015772 ]], shape=(3, 2), dtype=float32)

In [21]:
import tensorflow as tf

X = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor_8 = tf.random.shuffle(X)
print("\n--- Bài 8 ---")
print(tensor_8)

tensor_large = tf.random.normal([10, 10, 3])
tensor_9 = tf.image.random_crop(tensor_large, size=[5, 5, 3])
print("\n--- Bài 9 (Kích thước sau khi cắt) ---")
print(tensor_9.shape)

x = tf.random.uniform([5], minval=0, maxval=10)
y = tf.random.uniform([5], minval=0, maxval=10)
tensor_10 = tf.where(x < y, x + y, x - y)
print("\n--- Bài 10 ---")
print("x =", x.numpy())
print("y =", y.numpy())
print("Kết quả:", tensor_10.numpy())

x_mat = tf.random.uniform([3, 2], minval=5, maxval=10)
y_mat = tf.random.uniform([2, 3], minval=15, maxval=20)
xy_prod = tf.matmul(x_mat, y_mat)
diag_x = tf.linalg.diag_part(xy_prod)
tensor_11 = xy_prod + tf.linalg.diag(diag_x)
print("\n--- Bài 11 ---")
print(tensor_11)

--- Bài 8 ---
tf.Tensor(
[[3 4]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)

--- Bài 9 (Kích thước sau khi cắt) ---
(5, 5, 3)

--- Bài 10 ---
x = [2.0149505 5.6497097 2.9488897 6.9403076 5.4602585]
y = [6.009772   7.235434   3.5464299  0.75407386 3.6467218 ]
Kết quả: [ 8.024722  12.885143   6.4953194  6.1862335  1.8135366]

--- Bài 11 ---
tf.Tensor(
[[409.039   187.96141 207.89417]
 [306.44708 562.77344 313.99997]
 [211.55727 194.3565  431.55133]], shape=(3, 3), dtype=float32)

In [22]:
import tensorflow as tf

print("--- Bài 12 ---")

x = tf.random.uniform([3, 2, 2], minval=1, maxval=10)
y = tf.random.uniform([3, 2, 2], minval=1, maxval=10)

@tf.function
def tinh_toan_graph(a, b):
    tong = a + b
    hieu = a - b
    tich = a * b
    thuong = a / b
    return tong, hieu, tich, thuong

kq_tong, kq_hieu, kq_tich, kq_thuong = tinh_toan_graph(x, y)
print("Tổng:\n", kq_tong.numpy())
print("Hiệu:\n", kq_hieu.numpy())

print("\n--- Bài 13 ---")

class ModelTong(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return a + b

model_tong = ModelTong()
print("Tổng x + y:\n", model_tong(x, y).numpy())

print("\n--- Bài 14 ---")

class ModelHieuTich(tf.Module):
    @tf.function
    def __call__(self, a, b):
        hieu = a - b
        tich = a * b
        return hieu, tich

model_hieu_tich = ModelHieuTich()
kq_h, kq_t = model_hieu_tich(x, y)
print("Hiệu x - y:\n", kq_h.numpy())
print("Tích x * y:\n", kq_t.numpy())


print("\n--- Bài 15 ---")

class ModelChuVi(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return (a + b) * 2

model_cv = ModelChuVi()
chieu_dai = tf.constant([5.0, 10.0])
chieu_rong = tf.constant([3.0, 4.0])
print("Chu vi P:", model_cv(chieu_dai, chieu_rong).numpy())


print("\n--- Bài 16 ---")

class ModelDienTichHộp(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        s_xung_quanh = (a + b) * c * 2
        s_toan_phan = (a * b) * 2 + s_xung_quanh
        return s_xung_quanh, s_toan_phan

model_hop = ModelDienTichHộp()
a = tf.constant([2.0])
b = tf.constant([3.0])
c = tf.constant([4.0])

s_xq, s_tp = model_hop(a, b, c)
print("Diện tích xung quanh:", s_xq.numpy())
print("Diện tích toàn phần:", s_tp.numpy())

--- Bài 12 ---
Tổng:
 [[[11.205386  15.112577 ]
  [13.089567  11.068628 ]]

 [[14.198086   9.281561 ]
  [12.355234   7.5359125]]

 [[ 6.668626  14.445803 ]
  [11.613842   9.351475 ]]]
Hiệu:
 [[[-6.4380693  -3.4781108 ]
  [ 3.0146198  -3.776679  ]]

 [[ 2.6726031  -6.659117  ]
  [-2.5429764   2.3833039 ]]

 [[ 0.36572337 -3.9654903 ]
  [ 2.3729835   0.6476345 ]]]

--- Bài 13 ---
Tổng x + y:
 [[[11.205386  15.112577 ]
  [13.089567  11.068628 ]]

 [[14.198086   9.281561 ]
  [12.355234   7.5359125]]

 [[ 6.668626  14.445803 ]
  [11.613842   9.351475 ]]]

--- Bài 14 ---
Hiệu x - y:
 [[[-6.4380693  -3.4781108 ]
  [ 3.0146198  -3.776679  ]]

 [[ 2.6726031  -6.659117  ]
  [-2.5429764   2.3833039 ]]

 [[ 0.36572337 -3.9654903 ]
  [ 2.3729835   0.6476345 ]]]
Tích x * y:
 [[[21.027985 54.07319 ]
  [40.56221  27.062807]]

 [[48.61071  10.450885]
  [36.546272 12.777459]]

 [[11.084205 48.239025]
  [32.312572 21.757662]]]

--- Bài 15 ---
Chu vi P: [16. 28.]

--- Bài 16 ---
Diện tích xung quanh: [40.]
Diện tích toàn phần: [52.]

In [23]:
import tensorflow as tf

print("--- Bài 17 ---")

class ModelChungMinhSongSong(tf.Module):
    @tf.function
    def __call__(self, AD, BC, AB, CD):
        dieu_kien_1 = tf.equal(AD, BC)
        dieu_kien_2 = tf.equal(AB, CD)

        ad_song_song_bc = tf.logical_and(dieu_kien_1, dieu_kien_2)
        return ad_song_song_bc

model_17 = ModelChungMinhSongSong()

AD_test = tf.constant([5.0, 5.0])
BC_test = tf.constant([5.0, 4.0])
AB_test = tf.constant([3.0, 3.0])
CD_test = tf.constant([3.0, 3.0])

print("Kết quả chứng minh AD // BC:", model_17(AD_test, BC_test, AB_test, CD_test).numpy())


print("\n--- Bài 18 ---")

class ModelChungMinhBangNhau(tf.Module):
    @tf.function
    def __call__(self, AD, BC, ad_song_song_bc):
        dieu_kien_1 = tf.equal(AD, BC)
        dieu_kien_2 = ad_song_song_bc

        ab_bang_cd = tf.logical_and(dieu_kien_1, dieu_kien_2)
        return ab_bang_cd

model_18 = ModelChungMinhBangNhau()

AD_test2 = tf.constant([6.0, 6.0])
BC_test2 = tf.constant([6.0, 6.0])
song_song_test = tf.constant([True, False])

print("Kết quả chứng minh AB = CD:", model_18(AD_test2, BC_test2, song_song_test).numpy())

--- Bài 17 ---
Kết quả chứng minh AD // BC: [ True False]

--- Bài 18 ---
Kết quả chứng minh AB = CD: [ True False]

In [24]:
import tensorflow as tf

print("--- Bài 19 ---")

class ModelChungMinhTrungDiem(tf.Module):
    @tf.function
    def __call__(self, AM, MB, AN, NC, mn_song_song_bc):
        dieu_kien_1 = tf.equal(AM, MB)

        dieu_kien_2 = mn_song_song_bc

        la_trung_diem = tf.logical_and(dieu_kien_1, dieu_kien_2)

        return la_trung_diem

model_19 = ModelChungMinhTrungDiem()

AM_test = tf.constant([4.0, 4.0])
MB_test = tf.constant([4.0, 5.0])
AN_test = tf.constant([3.0, 3.0])
NC_test = tf.constant([3.0, 3.0])
song_song_test = tf.constant([True, True])

print("Kết quả chứng minh NA = NC:", model_19(AM_test, MB_test, AN_test, NC_test, song_song_test).numpy())

--- Bài 19 ---
Kết quả chứng minh NA = NC: [ True False]